CREATE TABLE IF NOT EXISTS WarPlayers (
	Id INTEGER PRIMARY KEY,
	WarId INTEGER NOT NULL,
	WarriorId INTEGER NOT NULL,
	Position INTEGER NOT NULL,
	FirstAttackId INTEGER NOT NULL,
	SecondAttackId INTEGER NOT NULL,
	FailedWarFault BOOLEAN NULL,
	FOREIGN KEY(WarId) REFERENCES Wars(Id),
	FOREIGN KEY(WarriorId) REFERENCES Warriors(Id),
	UNIQUE(WarId, WarriorId)
)