CREATE TABLE IF NOT EXISTS Warriors (
	Id INTEGER PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Hash NVARCHAR(10) NULL,
	TownHallLevel INTEGER NOT NULL,
	TownHallLevelMaturity INTEGER NOT NULL,
	ClanId INTEGER NOT NULL,
	ArrivalDate DATETIME NOT NULL,
	FOREIGN KEY(ClanId) REFERENCES Clans(Id)
)